server:
  port: 8288
spring:
  application:
    name: gemini-cache-example
  redis:
    port: 6379
logging:
  level:
    ROOT: info
    com:
      mirson: info
    org:
      springframework: info

# Redis 缓存配置信息
app.cache.enable: true
# 是否开启二级缓存（开启Caffeine）
app.cache.enableSecondCache: true
# Redis线程池最大连接数（默认为16）
app.cache.redis.executor.maxPoolSize: 16
# Redis线程池核心连接数（默认为8）
app.cache.redis.executor.corePoolSize: 8
# Redis线程池线程空闲存活有效时间（单位：秒， 默认30秒）
app.cache.redis.executor.aliveTime: 30
# Redis线程池线程池队列大小（默认1000）
app.cache.redis.executor.queueCapacity: 1000
# Redis连接池最大数量
app.cache.redis.pool.maxSize: 100
# Redis连接池最小空闲连接
app.cache.redis.pool.minIdleSize: 10
# Redis缓存全局超时时间（单位：秒）
app.cache.redis.global.expire: 60
# Redis连接池最大等待时间
app.cache.redis.pool.maxWaitMills: 3000
# Redis单机连接地址 （单机与集群方式二选一，优先单机）
#app.cache.redis.host: redis.kyeapi.com
# Redis单机连接端口
app.cache.redis.port: 6379
# Redis 集群连接地址信息 （单机与集群方式二选一，优先单机）
app.cache.redis.clusterNodes: 10.10.20.101:7000,10.10.20.101:7001,10.10.20.102:7000,10.10.20.102:7001,10.10.20.103:7000,10.10.20.103:7001
# Redis连接密码
app.cache.redis.password: Redis1234{}
# Redis连接池超时时间（单位：毫秒， 包括连接与读取超时时间）
app.cache.redis.pool.timeout: 3000
# Redis数据库编号（单机方式才生效）
app.cache.redis.database: 7
# Redis存储， 是否开启压缩模式
app.cache.redis.useCompression: true
# caffeine缓存超时时间（建议与业务数据的TTL超时时间一致）
app.cache.caffeine.expireAfterWrite: 30000